name: test-build-publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'    # only semantic-version tags like v1.2.3

permissions:
  contents: read
  id-token: write                 # needed for PyPI trusted publishing

jobs:
  test-build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install project & test deps
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install build pytest

    - name: Run tests
      run: pytest -q

    - name: Build sdist and wheel
      run: python -m build -o dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip-existing: true
        verbose: true
